Add devise
ilyassatlassi/Blog-app pull request #9
Opened 2023-06-21 20:19 UTC by ilyassatlassi

###HI, Reviewer 👋👋👋

In This PR:
- -Remove the `current_user` method in `ApplicationController`, devise will provide us with one.
- Install and setup the devise.
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed passwords should be stored in the database.
  - Ask for confirmation by email.
  - Can reset password.

2023-06-21 20:34 UTC, VICTOR-CHUKWU requested changes
Hi @ilyassatlassi  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 20:34 UTC, VICTOR-CHUKWU commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] when i want to signup I get an error that name is required, but there is no input for name, kindly fix that
![Screenshot from 2023-06-21 21-30-27](https://github.com/ilyassatlassi/Blog-app/assets/66097371/5b8499f2-386c-4e31-8526-31ac74c3b4b6)

2023-06-22 01:10 UTC, Owusu-Desmond approved these changes
Hi @ilyassatlassi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
📌 Linters are passing ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 README file is akay ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 01:10 UTC, Owusu-Desmond commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [OPTIONAL ]  Please from the project requirement, You should make sure that the app asks for confirmation of email so make sure that you add `:confirmable` and ensure that the user email is confirmed before the signup/login successful

2023-06-22 07:48 UTC, merged